# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  database: simple_cms_development
  username: dhafer

test:
  adapter: postgresql
  database: simple_cms_test
  username: dhafer

production:
  adapter: postgresql
  database: simple_cms_production
